title: Preferences API
key: preferences
order: 0
version: 
baseUri: https://api.mercadopago.com
/checkout/preferences:
  methods:
    - post
/checkout/preferences/{id}:
  methods:
    - get
    - put
/checkout/preferences/search:
  methods:
    - get