repos:
  - repo: https://github.com/melisource/fury_websec-git-hooks
    rev: v1.1.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]
