language: ruby

rvm:
  - 2.5.2
node_js:
  - 7
  
sudo: required

branches:
  only:
    - master

before_install:
  - rm /bin/sh && ln -s /bin/bash /bin/sh
  - sudo apt-get install -y tree
  - sudo apt-get install -y sed
  - sudo add-apt-repository -y ppa:chris-lea/node.js 
  - sudo apt-get update 
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - bash -c "source ~/.profile"
  - echo "$(nvm --version)"
  - nvm install node
  
install:
  - git clone -b installing-devsite https://$USER_TOKEN@github.com/mercadolibre/mercadopago-devsite.git  
  - mkdir /home/travis/build/mercadolibre 
  - sudo mv mercadopago-devsite /home/travis/build/mercadolibre/mercadopago-devsite
  - rm -rf /home/travis/build/mercadolibre/mercadopago-devsite/src/source
  - (cd /home/travis/build/mercadolibre/mercadopago-devsite && git clone -b installing-devsite https://$USER_TOKEN@github.com/mercadopago/devsite-frontend.git source)
  - cp -R /home/travis/build/mercadopago/devsite-docs/. /home/travis/build/mercadolibre/mercadopago-devsite/src/source/docs/
  - (bash -c "nvm use node && cd /home/travis/build/mercadolibre/mercadopago-devsite/src/source && npm install")
  - (bash -c "nvm use node && cd /home/travis/build/mercadolibre/mercadopago-devsite/src/source && npm install gulp") 
  - (cd /home/travis/build/mercadolibre/mercadopago-devsite/ && bundle install)
  - echo "$(tree -L 3 /home/travis/build/)"
  - echo "$(tree -L 3 /home/travis/build/mercadolibre/mercadopago-devsite/)"
  - git config --global user.name "devsitebot"
  - git config --global user.email "devsitebot@ml.com" 
script:
  - (bash -c "nvm use node && cd /home/travis/build/mercadolibre/mercadopago-devsite/src/source && gulp svgo") 
  - (bash -c "cd /home/travis/build/mercadolibre/mercadopago-devsite && TARGET=test middleman deploy") 
   
  