language: ruby

rvm:
  - 2.5.2
node_js:
  - 7
  
sudo: required


before_install: 
  - sudo apt-get install -y tree
  - sudo apt-get install -y sed
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  
install:
  - git clone -b installing-devsite https://$USER_TOKEN@github.com/mercadolibre/mercadopago-devsite.git  
  - mkdir /home/travis/build/mercadolibre 
  - sudo mv mercadopago-devsite /home/travis/build/mercadolibre/mercadopago-devsite
  - rm -rf /home/travis/build/mercadolibre/mercadopago-devsite/src/source
  - (cd /home/travis/build/mercadolibre/mercadopago-devsite && git clone -b installing-devsite https://$USER_TOKEN@github.com/mercadopago/devsite-frontend.git source)
  - cp -R /home/travis/build/mercadopago/devsite-docs/. /home/travis/build/mercadolibre/mercadopago-devsite/src/source/docs/
  - (bash -c "nvm use node && cd /home/travis/build/mercadolibre/mercadopago-devsite/src/source && npm install")
  - (bash -c "nvm use node && cd /home/travis/build/mercadolibre/mercadopago-devsite/src/source && npm install gulp") 
  - (cd /home/travis/build/mercadolibre/mercadopago-devsite/ && bundle install)
  - echo "$(tree -L 3 /home/travis/build/)"
  - echo "$(tree -L 3 /home/travis/build/mercadolibre/mercadopago-devsite/)"
  - git config --global user.name "devsitebot"
  - git config --global user.email "devsitebot@ml.com" 
script:
  - (bash -c "nvm use node && cd /home/travis/build/mercadolibre/mercadopago-devsite/src/source && gulp svgo") 
  - (bash -c "cd /home/travis/build/mercadolibre/mercadopago-devsite && TARGET=test middleman deploy") 
   
  