language: bash
  
sudo: required


before_install: 
  - sudo apt-get install -y tree
  - sudo apt-get install -y sed
  - sudo apt-get install -y hub
  
install:
  - git config --global user.name "devsitebot"
  - git config --global user.email "devsitebot@ml.com" 
  - git clone -b installing-devsite https://$USER_TOKEN@github.com/mercadolibre/fury_mercadopago-devsite.git
  - (cd fury_mercadopago-devsite/ && git submodule update --init --recursive) 
  - (cd fury_mercadopago-devsite/src/source/docs && git checkout $TRAVIS_BRANCH)
  - (cd fury_mercadopago-devsite/src/source && git add . && git commit -m "updating docs reference" && git push origin master)
  - (cd fury_mercadopago-devsite/ && git branch feature-$TRAVIS_BRANCH)
  - (cd fury_mercadopago-devsite/ && git checkout feature-$TRAVIS_BRANCH)
  - (cd fury_mercadopago-devsite/ && git add . && git commit -m "updating source reference" && git push origin feature-$TRAVIS_BRANCH)
  - (cd fury_mercadopago-devsite/ && hub pull-request -b feature-$TRAVIS_BRANCH -h master)
  
script: 
  - (bash -c " echo no tests ") 
   
  