title: Advanced Payments
key: advanced_payments
version: v1
baseUri: https://api.mercadopago.com/
/advanced_payments:
  methods:
    - post
/advanced_payments/{id}:
  methods:
    - get
    - put
/advanced_payments/{id}/refunds:
  methods:
    - post
/advanced_payments/{id}/disbursements/{disbursement_id}/refunds:
  methods:
    - post
/advanced_payments/{id}/disburses:
  methods:
    - post
/advanced_payments/{id}/disbursements/{disbursement_id}/disburses:
  methods:
    - post
/advanced_payments/{id}/search:
  methods:
    - get