title: Payments API
version: v1
baseUri: https://api.mercadopago.com/
documentation:
  es:
    title: Pagos
    body: API de pagos.
  en:
    title: Payments
    body: Payments API
  pt:
    title: Pagamentos
    body: API do Pagamentos 
/payments:
  - post
/payments/{id}:
  - get
  - put
/payments/search:
  - get