openapi: 3.0.0
servers:
  - url: https://api.mercadopago.com
info:
  title: Mercado Pago API Reference
  version: '1.0'
paths:
  /v1/identification_types:
    get:
      tags:
        - $ref: '#/tags/checkout-pro'
      summary: Get document types
      description: Consult all the types of documents available by country and get a list with the ID and details of each one
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: CPF
                      description: Identification type id.
                    name:
                      type: string
                      example: CPF
                      description: Identification type name.
                    type:
                      type: string
                      example: number
                      description: Identification number data type.
                    min_length:
                      type: number
                      example: 11
                      description: Identification number min length.
                    max_length:
                      type: number
                      example: 11
                      description: Identification number max length
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorKey:
                    type: string
                    enum:
                      - 1001--Public-key-not-found-
        '401':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorKey:
                    type: string
                    enum:
                      - 1000--The-credentials-are-required-
        '404':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorKey:
                    type: string
                    enum:
                      - 1004--Identification-types-not-found-
