title: Stores
key: stores
version: ' '
baseUri: https://api.mercadopago.com/
/users/{id}/stores:
  methods:
    - post
/users/{id}/stores/{store_id}:
  methods:
    - put
    - delete
/users/{id}/stores/search:
  methods:
    - get