title: Stores API
key: stores
version:
baseUri: https://api.mercadopago.com
/users/{user_id}/stores:
  methods:
    - post
/stores/{id}:
  methods:
    - get
/users/{user_id}/stores/{id}:
  methods:
    - put
    - delete
/users/{user_id}/stores/search:
  methods:
    - get