title: Payments API
version: 1.0
baseUri: https://api.mercadopago.com
documentation:
  - title: Pagos # es
    body: API de Pagos
  - title: Payments # en
    body: Payments API
  - title: Pagamentos # pt
    body: API do Pagamentos
uses:
  Payments: descriptors/payment.raml
/payments:
  post:
  put:
  /{id}:
    get:
      responses:
        200:
          application/json:
            type: Payment
