type: object
properties:
    id:
        type: string
        description:
            es: Indentificador unico de la preferencia (UUID)
            en: Preference ID (UUID)
    items:
        type: object
        description:
            en: Items information
            es: Informacion sobre los Items 
        properties:
            id:
                description:
                    en: Item ID
                    es: Identificador unico del Item
                type: string
            title: 
                description:
                    en: Item title. It will be displayed in the payment process.
                    es: Titulo del Item, esto sera mostrado en el proceso de pago.
                type: string
            description:
                description:
                    en: Item description
                    es: Descripcion del Item
                type: string
            picture_url:
                description:
                    en: Item image URL
                    es: Url de la imagen del Item
                type: string
            category_id:
                description:
                    en: Item category ID
                    es: Codigo de categoria del Item
                type: string
            quantity: 
                description:
                    en: Quantity
                    es: Cantidad
                type: integer
            currency_id:
                description:
                    en: Currency ID. ISO_4217 code
                    es: Codigo de la moneda. ISO_4217 code
                type: string
            unit_price: 
                description:
                    en: Unit price
                    es: Precio unitario
                type: float
    payer:
        description:
            en: Buyer Information
            es: Informacion del comprador
        type: object 
        properties:
            name:
                description:
                    en: Buyer name
                    es: Nombre del comprador
                type: string
            surname:
                description:
                    en: Buyer lastname
                    es: Apellido del comprador
                type: string
            email: 
                description:
                    en: Buyer e-mail address
                    es: Correo electornico del comprador
                type: string
            phone:
                description:
                    en: Buyer phone
                    es: Telefono del comprador
                type: object
                properties:
                    area_code:
                        description:
                            en: Area Code
                            es: Codigo de Area
                        type: string
                    number:
                        description:
                            en: Number
                            es: Numero
                        type: string
            identification:
                description:
                    en: Personal identification
                    es: Identificacion personal
                type: object
                properties:
                    type:
                        description:
                            en: Identification Type
                            es: Tipo de documento
                        type: string
                    number:
                        description:
                            en: Identification Number
                            es: Numero de Documento
                        type: string
            address:
                description:
                    en: Buyer address
                    es: Direccion del comprador
                type: object
                properties:
                    zip_code:
                        description:
                            en: ZipCode
                            es: Codigo Postal
                        type: string
                    street_name:
                        description:
                            en: Street Name
                            es: Nombre de la Calle
                        type: string
                    street_number:
                        description:
                            en: Street Number
                            es: Numeracion
                        type: integer
    payment_methods:
        description:
            en: Set up payment methods to be excluded from the payment process
            es: Definir los metodos de pago que seran excluidos del proceso de pago.
        type: object
        properties:
            excluded_payment_methods:
                description:
                    en: Payment methods not allowed in payment process (except account_money)
                    es: Metodos de Pago no soportados en el proceso de pago (Excepto dinero en cuenta de MercadoPago).
                type: object
                properties:
                    id: 
                        description:
                            en: Payment method ID
                            es: Identificador de cada metodo de pago excluido
                        type: string
            excluded_payment_types:
                description:
                    en: Payment types not allowed in payment process.
                    es: Tipos de pago no permitidos en el proceso de pago.
                type: object
                properties:
                    id: 
                        description:
                            en: Payment type ID.
                            es: Identificador de cada tipo de pago excluido.
                        type: string
            default_payment_method_id:
                description:
                    en: Payment method to be preferred on the payments methods list.
                    es: Metodo de pago preferido en el listado de metodos de pago.
                type: string
            installments:
                description:
                    en: Maximum number of credit card installments to be accepted.
                    es: Maximo de cuotas aceptadas para pagos con tarjeta de credito.
                type: integer
            default_installments:
                description:
                    en: Prefered number of credit card installments
                    es: Numero de cuotas preferido para los pagos con tarjeta de credito.
                type: integer
    shipments:
        type: object
        properties:
            mode:
                description:
                    en: Shipment mode
                    es: Tipo de envio
                type: string
                enum:
                    custom:
                        es: Personalizado
                        en: Custom shipping
                    me2:
                        es: MercadoEnvios
                        en: MercadoEnvíos
                    not_specified:
                        es: Metodo de envio no especificado
                        en: Shipping mode not specified
            local_pickup:
                description:
                    en: "The payer have the option to pick up the shipment in your store (mode:me2, only)"
                    es: "Indica si comprador tiene la opcion de retiro en tienda. (Solo para modo de envio: me2)"
                type: boolean
            dimensions:
                description:
                    en: "Dimensions of the shipment in cm x cm x cm, gr (mode:me2, only)"
                    es: "Dimensiones del paquete enviado en cm x cm x cm, gr (Solo para modo de envio: me2)"
                type: string
            default_shipping_method:
                description:
                    en: "Select default shipping method in checkout (mode:me2, only)"
                    es: "Metodo de envio por defecto en el proceso de pago. (Solo para modo de envio: me2)"
                type: integer
            free_methods:
                description:
                    en: "Offer a shipping method as free shipping (mode: me2, only)"
                    es: "Ofrecer un metodo de envio gratuito. (Solo para modo de envio: me2)"
                type: object
                properties:
                    id:
                        description:
                            en: Shipping method ID
                            es: Identificador del metodo de envio gratuito.
                        type: integer
            cost:
                description:
                    en: "Shipment cost (mode: custom, only)"
                    es: "Costo de envio. (Solo para modo de envio: custom)"
                type: float
            free_shipping:
                description:
                    en: "Free shipping for mode: custom"
                    es: "Envio gratuito para el modo: custom"
                type: boolean
            receiver_address: 
                description: 
                    en: "Shipping address"
                    es: "Direccion de envio"
                type: object
                properties: 
                    apartment:
                        description:
                            en: Apartment
                            es: Departamento
                        type: string
                    floor:
                        description:
                            en: Floor
                            es: Piso
                        type: string
                    street_name:
                        description:
                            en: "Street Name"
                            es: "Nombre de la calle"
                        type: string
                    street_number:
                        description:
                            en: "Street Number"
                            es: Numeracion
                        type: integer
                    zip_code:
                        description:
                            en: "Zip Code"
                            es: "Codigo Postal"
                        type: string 
    back_urls:
        description:
            en: URLs to return to the sellers website
            es: URLs de retorno al sitio del vendedor una vez terminado el flujo de pagos.
        type: object
        properties:
            success:
                description:
                    en: Approved payment URL
                    es: URL para pagos aprobados
                type: string
            pending:
                description:
                    en: Pending payment URL
                    es: URL para pagos pendientes
                type: string
            failure:
                description:
                    en: Canceled payment URL
                    es: URL para pagos cancelados
                type: string
    notification_url:
        description:
            en: URL where you'd like to receive a payment notification.
            es: URL en la cual se recibira la notificacion de pago.
        type: string
    init_point:
        description:
            en: Checkout access URL
            es: URL para iniciar el proceso de pago.
        type: string
    sandbox_init_point:
        description:
            en: Sandbox checkout access URL
            es: URL para iniciar el proceso de pago en modo sandbox.
        type: string
    date_created:
        description:
            en: Preference's creation date
            es: Fecha de creacion de la preferencia
        type: date
    operation_type:
        description:
            en: Operation data_type
            es: Tipo de operacion
        type: date
        enum:
            regular_payment:
                es: Pago normal
                en: Normal payment
            money_transfer:
                es: Solicitud de dinero
                en: Money request
    auto_return:
        description:
            en: If specified, your buyers will be redirected back to your site immediately after completing the purchase
            es: Este campo indica como los compradores seran redireccionados inmediatamente despues de completar una compra.
        type: string
        enum:
            approved:
                en: The redirection takes place only for approved payments
                es: La redireccion se realiza solo para los pagos aprobados.
            all:
                en: he redirection takes place only for approved payments, forward compatibility only if we change the default behavior
                es: La redireccion se realiza para todos los pagos.
    external_reference:
        description:
            en: Reference you can synchronize with your payment system
            es: Referencia con la que puedes sincronizar un pago con tu sistema.
        type: string
    expires:
        description:
            en: Boolean value that determines if a preference expire
            es: Determina si una preferencia expira.
        type: boolean
    expiration_date_from:
        description:
            en: Date since the preference will be active
            es: Fecha desde cual la preferencia estara activa.
        type: date
    expiration_date_to:
        description:
            en: Date when the preference will be expired
            es: Fecha para la expiracion de la preferencia.
        type: date
    collector_id:
        description:
            en: Your MercadoPago seller ID
            es: Tu codigo de vendedor de Mercado Pago
        type: integer
    client_id:
        description:
            en: Application owner ID that use MercadoLibre API
            es: Identificador del propietario de la aplicacion que usa el API de MercadoLibre
        type: integer
    marketplace:
        description:
            en: "Origin of the payment. Default value: NONE"
            es: "Origin del pago. Por defecto: NONE"
        type: string
    marketplace_fee:
        description:
            en: "Marketplace's fee charged by application owner. Default value: 0%"
            es: "Comision de Marketplace cobrado por el propietario de la aplicacion. Valor por defecto: 0%"
        type: float
    differential_pricing:
        description:
            en: Differential pricing configuration for this preference
            es: Configuracion de precio diferencial para esta preferencia.
        type: object
        properties:
            id: 
                description:
                    en: Differential pricing ID
                    es: Identificador de precio diferencial
                type: integer