
type: object
properties:
  payer:
    type: object
    description:
      es: Identifica al comprador
    required: true
    properties:
      id: 
        type: string
        description:
          es: Identificador del pagador asociado
      entity_type:
        type: string
        description:
          es: Entidad del Pagador, parametro valido solo para transferencias bancarias.
        enum:
          individual:
            es: Persona
          association:
            es: Asociación
      type:
        type: string
        description:
          es: Tipo de pagador (Solo para transferencias bancarias)
        enum:
          customer:
            es: El pagador es un cliente y pertenece al comercio
          registered:
            es: La cuenta corresponde a un usuario registrado en Mercado Pago
          guest:
            es: El pagador no tiene una cuenta
      email:
        type: string
        description:
          es: Correo electronico del pagador
      identification:
        type: object
        description:
          es: Identificacion personal del pagador
        properties:
          type:
            type: string
            description: 
              es: Tipo de documento
          number:
            type: string 
            description:
              es: Numero de documento
  binary_mode:
    type: boolean
    description:
      es: Cuando esta definido como verdadero, el pago solo puede estar en 2 estados (Aprobado o Rechazado), en otro caso el pago tambien peude pasar por el estado in_process.
  order:
    type: object
    properties:
      id:
        type: long
        description:
          es: ID asociado a la orden de compra
      type:
        type: string
        description: 
          es: Identificador de orden
          enum:
            mercadolibre:
              es: Esta es una orden de Mercado Libre
            mercadopago:
              es: Este es un merchant_order de Mercado Pago
  external_reference:
    type: string
    description: 
      es: ID obtenido por el comercio para identificar el pago en su sistema.
  description:
    type: string
    description: 
      es: Razon del pago o description del item
  metadata:
    type: object/json
    description: 
      es: Un objeto JSON valido puede ser adjuntado al pago para guardar atributos adicionales para el comercio.
  transaction_amount:
    type: float
    description: 
      es: Monto total de la transaccion
    required: true
  net_amount:
    type: float
    description:
      es: Monto neto de la transaccion (Solo para Colombia)
  taxes:
    type: object
    description:
      es: IVA (Impuesto al valor agregado), es una carga fiscal que recae sobre la venta de productos o la prestación de servicios dentro del territorio colombiano.
    properties:
      value:
        type: float
        description:
          es: Monto del impuesto
      type:
        type: string
        description:
          es: Tipo de impuesto
  coupon_amount:
    type: float
    description: 
      es: Monto total del cupon de descuento
  campaign_id:
    type: integer
    description: 
      es: Codigo de la campaña de descuentos
  coupon_code:
    type: string
    description: 
      es: Campaña de descuento con un codigo especifico.
  differential_pricing_id:
    type: integer
    description: 
      es: Codigo del esquema de absorcion del costo de financiamiento.
  application_fee:
    type: float
    description: 
      es: Comision cobrada por un Marketplace o una aplicacion de Mercado Pago
  capture:
    type: boolean
    description: 
      es: Determina si un pago debe ser capturado (true) o solo reservado (false)
  payment_method_id:
    type: string
    required: true
    description: 
      es: Metodo de pago elegido para realizar el pago.
  issuer_id:
    type: string
    description: 
      es: Emisor del metodo de pago. 
  token:
    type: string
    required: true
    description:
      es: Card Token ID
  statement_descriptor:
    type: string
    description:
      es: Texto de descripcion que aparecera en el recibo de pago.
  installments:
    type: integer
    description:
      es: Cantidad de cuotas del pago
  notification_url:
    type: string
    description:
      es: URL donde Mercado Pago enviara notificaciones asociadasa a los cambios de estado del pago.
  callback_url:
    type: string
    description:
      es: URL donde Mercado Pago hara el final redirect (solo para transferencias bancarias)
  additional_info:
    type: object
    description:
      es: Informacion que permite mejorar los ratios de analisis de prevencion del fraude, trata de enviar la mayor informacion posible.
    properties:
      ip_address:
        description:
          es: IP desde el cual se realizo la transaccion (Solo para transferencias bancarias)
        type: string
      items:
        description:
          es: Lista de items a pagar
        type: object
        properties:
          id:
            type: string
            description:
              es: Codigo del item
          title:
            type: string
            description:
              es: Nombre del item
          description:
            type: string
            description:
              es: Descripcion del item
          picture_url:
            type: string
            description:
              es: Imagen del item
          category_id:
            type: string
            description:
              es: Categoria del item
          quantity:
            type: string
            description:
              es: Cantidad del item
          unit_price:
            type: string
            description:
              es: Precio unitario del item
      payer:
        description: 
          es: Informacion del comprador
        type: object
        properties:
          first_name:
            type: string
            description:
              es: Nombre del comprador
          last_name:
            type: string
            description:
              es: Apellido del comprador
          phone:
            type: string
            description:
              es: Telefono del comprador
          address:
            type: string
            description:
              es: Direccion del comprador
          registration_date:
            type: string
            description:
              es: Fecha de registro del comprador
      shipments:
        description:
          es: Informacion de Envio
        type: object
        properties:
          receiver_address:
            type: object
            description:
              es: Direccion del comprador 
            properties:
              zip_code:
                type: string
                description:
                  es: Codigo Zip
              street_name:
                type: string
                description:
                  es: Nombre de la calle
              street_number:
                type: string
                description:
                  es: Numero de domicilio
              floor:
                type: string
                description:
                  es: Piso
              apartment:
                type: string
                description:
                  es: Departamento
      barcode:
        type: object
        description:
          es: Informacion sobre el codigo de barras asociado a una transaccion
        properties:
          type:
            type: string
            description:
              es: Tipo de codificación
            enum:
              UCC/EAN128:
                es: Codifica la informacion usando la simbologia de 128
              Code128C:
                es: Codigo alfanumerico de alta densidad 
              Code39:
                es: Codigo de media densidad
          content:
            type: string
            description:
              es: Codigo de barras generados
          width: 
            type: integer
            description:
              es: Ancho del codigo de barras
          heght:
            type: integer
            description:
              es: Alto del codigo de barras
