title: Cards API
key: cards
version: v1
baseUri: https://api.mercadopago.com/
/customers/{customer_id}/cards:
  methods:
    - get
    - post
/customers/{customer_id}/cards/{id}:
  methods:
    - get
    - put
    - delete