---
type: object
properties:
- id:
    type: String
    description:
      en: Plan identifier
      es: Identificador de Plan de
      pt: Identificador de plano de
- application_fee:
    type: Float
    description:
      en: Fee collected by a marketplace or MercadoPago Application
      es: Cobrada por un mercado o MercadoPago Aplicación
      pt: Cobrança de taxa por um mercado ou Aplicação de MercadoPago
- status:
    type: String
    description:
      en: Plan status
      es: Situación del Plan de
      pt: Plano de status
    enum:
    - active:
        en: Customers may be suscribed to this plan
    - inactive:
        en: Customers may no longer be suscribed to this plan
    - cancelled:
        en: Customers may no longer be suscribed to this plan. Also, the subscriptions
          were cancelled.
- description:
    type: String
    description:
      en: Subscription plan reason or service title
      es: El plan de suscripción de la razón o título
      pt: Plano de subscrição razão ou de serviço, título de
- external_reference:
    type: String
    description:
      en: ID given by the merchant in their system
      es: IDENTIFICADOR dado por el comerciante en su sistema
      pt: IDENTIFICAÇÃO fornecida pelo anunciante em seu sistema
- date_created:
    type: Date(ISO_8601)
    description:
      en: Plan’s creation date
      es: Del Plan, la fecha de creación de
      pt: Plano data de criação
- last_modified:
    type: Date(ISO_8601)
    description:
      en: Last modified date
      es: Fecha de última modificación
      pt: Data da última modificação
- auto_recurring:
    type: Object
    description:
      en: Automatic charges configuration
      es: Los cargos automáticos de configuración
      pt: Automática de encargos de configuração
    properties:
    - frequency:
        type: Integer
        description:
          en: Amount of time (in days or months) for the execution of the next payment
          es: Cantidad de tiempo (en días o meses) para la ejecución de la siguiente
            pago
          pt: Quantidade de tempo (em dias ou meses) para a execução do próximo pagamento
    - frequency_type:
        type: String
        description:
          en: 'Indicates the period of time. Might be: ''days'' or ''months'''
          es: 'Indica el período de tiempo. Podría ser: ''días'' o ''meses'''
          pt: 'Indica o período de tempo. Pode ser: ''dias'' ou ''meses'''
        enum:
        - days:
            en: Collect every X days (X given by the frequency)
        - months:
            en: Collect every X months (X given by the frequency)
    - transaction_amount:
        type: Float
        description:
          en: The amount to charge the customer on each period
          es: La cantidad a cobrar al cliente en cada período
          pt: O valor a cobrar ao cliente em cada período de
    - currency_id:
        type: String(3)
        description:
          en: ID of the currency used in every payment, in ISO 4217
          es: ID de la moneda que se utiliza en cada uno de los pagos, en la norma
            ISO 4217
          pt: ID do a moeda utilizada em cada pagamento, a norma ISO 4217
        enum:
        - ARS:
            en: Argentine peso
        - BRL:
            en: Brazilian real
        - VEF:
            en: Venezuelan strong bolivar
        - CLP:
            en: Chilean peso
        - MXN:
            en: Mexican peso
        - COP:
            en: Colombian peso
        - PEN:
            en: Peruvian sol
        - UYU:
            en: Uruguayan peso
    - repetitions:
        type: Integer
        description:
          en: Quantity of payments to be done during the subscription validity (number
            of installments)
          es: La cantidad de pagos a realizar durante la suscripción de validez (número
            de cuotas)
          pt: Quantidade de pagamentos a ser feito durante a assinatura de validade
            (número de parcelas)
    - debit_date:
        type: Integer(1..31)
        description:
          en: Date of month when the payment should be issued (only for monthly based
            plans)
          es: Fecha de mes, cuando el pago debe ser emitido (sólo para el mensual
            en función de los planes)
          pt: Data do mês em que o pagamento deve ser emitido (apenas para mensal
            em planos)
    - free_trial:
        type: Object
        description:
          en: Period to give the service for free (bonus period)
          es: Período para dar el servicio de forma gratuita (período de bono)
          pt: Período para prestar o serviço de graça (período de bônus)
        properties:
        - frequency:
            type: Integer
            description:
              en: Amount of time (in days or months) for the free trial period
              es: Cantidad de tiempo (en días o meses) para el período de prueba
              pt: Quantidade de tempo (em dias ou meses) para o período de teste gratuito
        - frequency_type:
            type: String
            description:
              en: 'Indicates the period of time. Might be: ''days'' or ''months'''
              es: 'Indica el período de tiempo. Podría ser: ''días'' o ''meses'''
              pt: 'Indica o período de tempo. Pode ser: ''dias'' ou ''meses'''
            enum:
            - days:
                en: Free trial for X days (X given by the frequency)
            - months:
                en: Free trial for X months (X given by the frequency)
- live_mode:
    type: Boolean
    description:
      en: Whether the plan and the later subscriptions will be processed in sandbox
        or in production mode
      es: Si el plan y la posterior suscripciones serán procesados en el espacio o
        en el modo de producción
      pt: Se o plano e a posterior inscrições serão processadas na caixa de areia
        ou em modo de produção
- setup_fee:
    type: Float
    description:
      en: Amount to be charged once, during de subscription process. Useful to charge
        an installation cost or a sign up price.
      es: El monto a cobrar una vez, durante el de proceso de suscripción. Útil para
        cargar un costo de instalación o una señal de precio.
      pt: Valor a ser cobrado de uma só vez, durante processo de inscrição. Útil para
        cobrar um custo de instalação ou um sinal de preço.
- metadata:
    type: Object
    description:
      en: Valid JSON that can be attached to the plan to record additional attributes
        of the merchant
      es: Válido JSON que se puede adjuntar el plan de registro de atributos adicionales
        del comerciante
      pt: Válido JSON que pode ser anexado ao plano de gravar atributos adicionais
        do estabelecimento
