---
type: object
properties:
- id:
    type: String
    description:
      en: Subscription identifier
      es: Identificador de suscripción
      pt: Assinatura identificador
- plan_id:
    type: String
    description:
      en: Plan to which the subscription belongs
      es: El Plan al que pertenece la suscripción
      pt: Plano para que a assinatura pertence
- payer:
    type: Object
    description:
      en: Identifies the buyer
      es: Identifica el comprador
      pt: Identifica o comprador
    properties:
    - id:
        type: Integer
        description:
          en: Identification of the associated payer
          es: Identificación de los asociados pagador
          pt: Identificação do associado pagante
    - type:
        type: String
        description:
          en: Identification type of the associated payer
          es: Identificación del tipo de los asociados pagador
          pt: Tipo de identificação do associado pagante
        enum:
        - customer:
            en: Payer is a Customer and belongs to the collector
        - registered:
            en: The account corresponds to a MercadoPago registered user
    - email:
        type: String
        description:
          en: Customer's email
          es: Cliente de correo electrónico
          pt: Cliente de e-mail
    - identification:
        type: Object
        description:
          en: Personal identification
          es: De identificación Personal
          pt: Identificação pessoal
        properties:
        - type:
            type: String
            description:
              en: Identification type
              es: Identificación del tipo de
              pt: Tipo de identificação
        - number:
            type: String
            description:
              en: Identification number
              es: Número de identificación
              pt: Número de identificação
- application_fee:
    type: Float
    description:
      en: Fee collected by a marketplace or MercadoPago Application
      es: Cobrada por un mercado o MercadoPago Aplicación
      pt: Cobrança de taxa por um mercado ou Aplicação de MercadoPago
- status:
    type: String
    description:
      en: Subscription status
      es: Estado de la suscripción
      pt: Status da inscrição
    enum:
    - authorized:
        en: The subscription is running
    - paused:
        en: No charges will be made during this state (stop debit)
    - finished:
        en: The subscription ended at the proper date, and it processed all its invoices
    - cancelled:
        en: The subscription was cancelled prior to its end date
- description:
    type: String
    description:
      en: Subscription plan reason or service title
      es: El plan de suscripción de la razón o título
      pt: Plano de subscrição razão ou de serviço, título de
- external_reference:
    type: String
    description:
      en: ID given by the merchant in their system
      es: IDENTIFICADOR dado por el comerciante en su sistema
      pt: IDENTIFICAÇÃO fornecida pelo anunciante em seu sistema
- date_created:
    type: Date(ISO_8601)
    description:
      en: Subscription creation date
      es: Suscripción fecha de creación
      pt: Criação de assinatura data
- last_modified:
    type: Date(ISO_8601)
    description:
      en: Last modified date
      es: Fecha de última modificación
      pt: Data da última modificação
- live_mode:
    type: Boolean
    description:
      en: Whether the subscription will be processed in sandbox or in production mode
      es: Si la suscripción será procesada en el espacio o en el modo de producción
      pt: Se a inscrição será processada na caixa de areia ou em modo de produção
- start_date:
    type: Date(ISO_8601)
    description:
      en: When billing process begins to happen
      es: Cuando el proceso de facturación empieza a suceder
      pt: Quando o processo de faturamento começa a acontecer
- end_date:
    type: Date(ISO_8601)
    description:
      en: When billing process stops (the subscription finishes)
      es: Cuando el proceso de facturación de paradas (la suscripción acabados)
      pt: Quando o processo de faturamento pára (a subscrição termina)
- metadata:
    type: Object
    description:
      en: Valid JSON that can be attached to the subscription to record additional
        attributes of the merchant
      es: Válido JSON que puede ser conectado a la suscripción de registro de atributos
        adicionales del comerciante
      pt: Válido JSON que pode ser anexado à inscrição para registro atributos adicionais
        do estabelecimento
- charges_detail:
    type: Object
    description:
      en: Summarizes the subscription status at the given time
      es: Resume el estado de la suscripción en el momento dado
      pt: Resume o estado da subscrição, em dado momento
    properties:
    - invoices:
        type: List(Object)
        description:
          en: All generated invoices
          es: Todas las facturas generadas
          pt: Todos gerado faturas
        properties:
        - period:
            type: Date(ISO_8601)
            description:
              en: Date of time period charged or to be charged
              es: Fecha de período de tiempo cargado o para ser cargada
              pt: Data de período de tempo debitado ou para ser cobrado
        - id:
            type: String
            description:
              en: Invoice identifier
              es: Identificador de la factura
              pt: Nota fiscal identificador
    - last_charged_date:
        type: Date(ISO_8601)
        description:
          en: Date of last processed invoice
          es: Fecha de la última factura procesada
          pt: Data da última processado fatura
    - last_charged_amount:
        type: Float
        description:
          en: Amount of last processed invoice
          es: Importe de la última factura procesada
          pt: Valor da última processado fatura
    - pending_charge_amount:
        type: Float
        description:
          en: Amount to be charged during the rest of the subscription
          es: Cantidad a pagar durante el resto de la suscripción
          pt: Valor a ser cobrado durante o resto da subscrição
    - pending_charge_periods:
        type: Integer
        description:
          en: Quantity of invoices to be charged during the rest of the subscription
          es: Cantidad de facturas para ser cargado durante el resto de la suscripción
          pt: A quantidade de faturas para cobrança durante o resto da subscrição
    - charged_amount:
        type: Float
        description:
          en: Amount already charged by this subscription
          es: El importe ya cobrado por esta suscripción
          pt: Valor já cobrado por esta subscrição
    - charged_periods:
        type: Integer
        description:
          en: Quantity of invoices already charged by this subscription
          es: Cantidad de facturas ya imputado por esta suscripción
          pt: A quantidade de faturas já cobrado por esta subscrição
    - debt_amount:
        type: Float
        description:
          en: Amount that this subscription was unable to collect
          es: Cantidad que esta suscripción no pudo recoger
          pt: Quantidade que essa inscrição foi capaz de coletar
    - debt_periods:
        type: Integer
        description:
          en: Quantity of invoices that this subscription was unable to collect
          es: La cantidad de facturas que esta suscripción no pudo recoger
          pt: A quantidade de faturas que essa inscrição foi capaz de coletar
    - next_payment_date:
        type: Date(ISO_8601)
        description:
          en: Date of next charge or charging retry on the current invoice
          es: Próxima fecha de carga o la carga de reintento de la factura actual
          pt: Data da próxima carga ou carregamento de repetição da nota fiscal atual
- setup_fee:
    type: Float
    description:
      en: Amount to be charged once, during de subscription process. Useful to charge
        an installation cost or a sign up price.
      es: El monto a cobrar una vez, durante el de proceso de suscripción. Útil para
        cargar un costo de instalación o una señal de precio.
      pt: Valor a ser cobrado de uma só vez, durante processo de inscrição. Útil para
        cobrar um custo de instalação ou um sinal de preço.
