title: Merchant Orders API
key: merchant_orders
baseUri: https://api.mercadopago.com
/merchant_orders:
  methods:
    - post
/merchant_orders/{id}:
  methods:
    - get
    - put
/merchant_orders/search:
  methods:
    - get