title: Merchant Orders API
key: merchant_orders
version: ''
baseUri: https://api.mercadopago.com/ 
/merchant_orders:
  methods:
    - post
    - search
/merchant_orders/{id}:
  methods:
    - get
    - put